# Generated by Django 5.2.13 on 2026-06-13 12:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panapplication',
            name='epan_pdf',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_epan),
        ),
    ]
