# Generated by Django 5.2.13 on 2026-06-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='panapplication',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pan_applications', to='app.retailer'),
        ),
    ]
