# Generated by Django 5.2.13 on 2026-06-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_panapplication_retailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCAdvanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('vehicle_class', models.CharField(blank=True, max_length=100)),
                ('maker_model', models.CharField(blank=True, max_length=200)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('rc_data', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
