# Generated by Django 5.2.13 on 2026-06-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rcadvanceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcadvanceapplication',
            name='service_type',
            field=models.CharField(default='advance', max_length=20),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='order_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='rc_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.retailer'),
        ),
        migrations.AlterField(
            model_name='rcadvanceapplication',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
