# Generated by Django 5.2.13 on 2026-07-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rcadvanceapplication_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLAllIndiaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('dl_number', models.CharField(max_length=20)),
                ('dob', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('dl_data', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_allindia_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
