# Generated by Django 5.2.5 on 2026-08-14 05:29

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dlallindiaapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLKarnatakaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('dl_number', models.CharField(blank=True, max_length=20)),
                ('dob', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('dl_data', models.JSONField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dl_karnataka/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='dl_karnataka/signatures/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_karnataka_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TailoringCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('father_husband_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluk', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('physical_handicap', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('highest_education', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app.models.upload_tailoring_photo)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to=app.models.upload_tailoring_id)),
                ('education_cert', models.FileField(blank=True, null=True, upload_to=app.models.upload_tailoring_cert)),
                ('amount', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailoring_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
