# Generated by Django 5.2.5 on 2026-08-14 05:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dlkarnatakaapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoringcertificateapplication',
            name='output_pdf',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_tailoring_output_pdf),
        ),
        migrations.AddField(
            model_name='tailoringcertificateapplication',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tailoringcertificateapplication',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
