# Generated by Django 5.2.5 on 2026-08-14 06:10

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_basiccomputercertificateapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdyamRegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('pan_card_no', models.CharField(blank=True, max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('working_member', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('annual_income', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('account_no', models.CharField(blank=True, max_length=20)),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_udyam_aadhaar)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_udyam_pan)),
                ('bank_passbook_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_udyam_passbook)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_udyam_output_pdf)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udyam_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
