# Generated by Django 5.2.5 on 2026-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cibilscoreapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='retailer',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
