# Generated by Django 5.2.5 on 2026-08-17 06:20

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_pantoaadhaarapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorCitizenApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('talluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app.models.upload_senior_photo)),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_senior_aadhaar)),
                ('blood_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_senior_blood)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_senior_output_pdf)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
