# Generated by Django 5.2.5 on 2026-08-17 07:10

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_gruhajyothidlinkapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhoomiPahaniLinkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('applicant_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('talluk', models.CharField(max_length=100)),
                ('hobli', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('survey_no', models.CharField(blank=True, max_length=50)),
                ('hissa_no', models.CharField(blank=True, max_length=50)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_bhoomi_pahani_link_output_pdf)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bhoomi_pahani_link_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
