# Generated by Django 5.2.5 on 2026-08-17 07:26

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ayushdownloadapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EShramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('relative_name', models.CharField(max_length=100)),
                ('social_category', models.CharField(max_length=50)),
                ('differently_abled', models.CharField(default='no', max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_division', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('staying_from', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('monthly_income', models.CharField(max_length=100)),
                ('online_working', models.CharField(default='no', max_length=10)),
                ('primary_occupation', models.CharField(max_length=100)),
                ('work_exp', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_eshram_output_pdf)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eshram_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
