PS C:\Users\ADMIN\Desktop\pan_project> git add .
warning: adding embedded git repository: pan_project/pan_project
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> pan_project/pan_project
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached pan_project/pan_project
hint:
hint: See "git help submodule" for more information.
hint: Disable this message with "git config set advice.addEmbeddedRepo false"
PS C:\Users\ADMIN\Desktop\pan_project> git commit -m "Add Karnataka Govt Services, Admin Services Directory, SSP Password Change, SSP Mobile Link, and Mobile to PAN Surepass API integration"
[main 82f164e6] Add Karnataka Govt Services, Admin Services Directory, SSP Password Change, SSP Mobile Link, and Mobile to PAN Surepass API integration
 1 file changed, 1 insertion(+)
 create mode 160000 pan_project/pan_project
PS C:\Users\ADMIN\Desktop\pan_project> git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/Leranmore123/smnath-.git'
PS C:\Users\ADMIN\Desktop\pan_project> 


# Generated by Django 5.2.5 on 2026-08-17 07:37

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_eshramdownloadapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMKisanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('application_type', models.CharField(default='e-KYC', max_length=50)),
                ('applicant_name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_pmkisan_output_pdf)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmkisan_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
