# Generated by Django 5.2.5 on 2026-08-17 07:47

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_naadakacheridownloadapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='YuvaNidhiApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('talluk', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('certificate_no', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('ration_card_no', models.CharField(blank=True, max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('disability', models.CharField(default='no', max_length=10)),
                ('markscard_10th', models.FileField(upload_to=app.models.upload_yuvanidhi_doc)),
                ('markscard_puc', models.FileField(blank=True, null=True, upload_to=app.models.upload_yuvanidhi_doc)),
                ('markscard_degree', models.FileField(upload_to=app.models.upload_yuvanidhi_doc)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to=app.models.upload_yuvanidhi_doc)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuvanidhi_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
