# Generated by Django 5.2.5 on 2026-08-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_sspmobilelinkapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToPanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('response_message', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_to_pan_applications', to='app.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
